name: alfred_interview
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  collection: ^1.17.2
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^11.1.3
  hive: ^2.2.3
  json_annotation: ^4.8.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  http_mock_adapter: ^0.6.0
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - .env
